### ISSUE TITLE
nextflow run on main branch

### ISSUE THREAD

**Issue by elizabethmcd** [Arcadia-Science/seqqc#3]
Out of curiosity after reviewing the recent PR I wanted to test the pipeline with `nextflow run Arcadia-Science/seqqc -profile test,docker --outdir test` and got the error: 
```
Project `Arcadia-Science/seqqc` is currently stickied on revision: main -- you need to explicitly specify a revision with the option `-r` in order to use it
```

Using the command `nextflow run Arcadia-Science/seqqc -profile test,docker -outdir test -r main` fixes this. 

However, this will either affect how we create templates or put in the documentation how to run the pipeline. Either: 
1. Go back to `master` branch convention since that's how `nf-core create` makes pipelines and evidently how `nextflow run` expects it
2. Just write in the documentation to include the `-r main` flag

**Comment by taylorreiter** [comment]
I switched the default branch back to master because I don't want to deal with switching over all of the failed linting.
